//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresse
    {
        public int ID_Adresse { get; set; }
        public string pays { get; set; }
        public string ville { get; set; }
        public string prefecture { get; set; }
        public string village { get; set; }
        public Nullable<System.DateTime> dateDebut { get; set; }
        public Nullable<System.DateTime> dateFin { get; set; }
        public Nullable<int> ID_Patient { get; set; }
        public Nullable<int> ID_Staff { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
