//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordonnance
    {
        public int ID_Ordonnance { get; set; }
        public string prescription { get; set; }
        public string medicament { get; set; }
        public Nullable<int> ID_Consultation { get; set; }
    
        public virtual Consultation Consultation { get; set; }
    }
}
